version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - .env

  web:
    build: .
    command: sh -c "sleep 10 && python manage.py migrate && echo 'from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username=\"admin2\", phone_number=\"1234567890\").exists() or User.objects.create_superuser(\"admin2\", phone_number=\"1234567890\", password=\"admin\")' | python manage.py shell && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - .env


volumes:
  postgres_data:

networks:
  my-network: